In [50]:
import pandas as pd
import numpy as np
import scipy.io
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC

### Data loading and preprocessing

In [51]:
import os

DATA_DIR = ''
if 'google.colab' not in str(get_ipython()) and "anuja" in os.environ.get('USER'):
    DATA_DIR = 'data/'
    

In [52]:
foof = pd.read_csv(DATA_DIR+"foof2features.csv")
foof = foof.rename(columns={"C1": "IDs" ,"C2": "Intercept", "C3": "Slope"})
foof

IDs  Intercept     Slope
0     NDARAA075AMK   0.986272  1.825774
1     NDARAA112DMH   1.486650  1.888544
2     NDARAA117NEJ   1.593155  2.095749
3     NDARAA947ZG5   0.703331  1.724831
4     NDARAA948VFH   0.918020  1.749441
...            ...        ...       ...
2037  NDARZN277NR6   1.351549  1.996940
2038  NDARZN578YDP   1.380795  2.036327
2039  NDARZN610GTY   0.339229  1.050644
2040  NDARZN677EYE   0.781225  1.470061
2041  NDARZN899JCM   0.464107  1.664433

[2042 rows x 3 columns]

In [53]:
data = scipy.io.loadmat(DATA_DIR+'x.mat')  
df = pd.DataFrame(data['x'].reshape((data['x'].shape[0], -1)))
columns = np.asarray([['Electrode %d - %d/2 Hz'%(i+1, j+1)] for i in range(data['x'].shape[1]) for j in range(data['x'].shape[2])])
df.columns = columns
df['IDs'] = foof['IDs']
df



(Electrode 1 - 1/2 Hz,)  (Electrode 1 - 2/2 Hz,)  \
0                7.707834e-12             1.512286e-10   
1                3.798713e-02             1.639433e-01   
2                2.104310e-06             4.299647e-05   
3                1.692639e-01             2.021357e-01   
4                8.332328e-06             1.552379e-04   
...                       ...                      ...   
2037             8.241315e-06             2.938160e-04   
2038             8.113400e-03             1.005675e-02   
2039             5.472767e-03             8.816325e-03   
2040             2.658455e-03             5.749806e-03   
2041             4.856385e-04             3.048976e-03   

      (Electrode 1 - 3/2 Hz,)  (Electrode 1 - 4/2 Hz,)  \
0                2.475735e-09             3.453763e-08   
1                2.897591e-01             2.097609e-01   
2                5.644195e-04             4.760137e-03   
3                2.273063e-01             2.406964e-01   
4                1.804338e-03             1.287033e-02   
...                       ...                      ...   
2037             4.641777e-03             3.249546e-02   
2038             1.237930e-02             1.513279e-02   
2039             1.629356e-02             3.226822e-02   
2040             1.180538e-02             2.300961e-02   
2041             1.546836e-02             5.645783e-02   

      (Electrode 1 - 5/2 Hz,)  (Electrode 1 - 6/2 Hz,)  \
0                4.554996e-07                 0.000007   
1                6.347556e-02                 0.027758   
2                2.579253e-02                 0.089799   
3                2.400039e-01                 0.225430   
4                5.615280e-02                 0.149809   
...                       ...                      ...   
2037             1.008094e-01                 0.138615   
2038             1.837070e-02                 0.022147   
2039             6.212373e-02                 0.108594   
2040             4.257369e-02                 0.074778   
2041             1.419824e-01                 0.245335   

      (Electrode 1 - 7/2 Hz,)  (Electrode 1 - 8/2 Hz,)  \
0                    0.000109                 0.001314   
1                    0.105298                 0.184513   
2                    0.201005                 0.290260   
3                    0.202278                 0.198154   
4                    0.244887                 0.247738   
...                       ...                      ...   
2037                 0.084707                 0.024339   
2038                 0.026515                 0.031525   
2039                 0.166461                 0.220594   
2040                 0.124685                 0.197358   
2041                 0.301591                 0.291822   

      (Electrode 1 - 9/2 Hz,)  (Electrode 1 - 10/2 Hz,)  ...  \
0                    0.009992                  0.045200  ...   
1                    0.130638                  0.163258  ...   
2                    0.276177                  0.196151  ...   
3                    0.228356                  0.181836  ...   
4                    0.163687                  0.094061  ...   
...                       ...                       ...  ...   
2037                 0.009157                  0.021386  ...   
2038                 0.037230                  0.043721  ...   
2039                 0.252412                  0.252807  ...   
2040                 0.296551                  0.423009  ...   
2041                 0.267454                  0.265932  ...   

      (Electrode 105 - 71/2 Hz,)  (Electrode 105 - 72/2 Hz,)  \
0                   2.990881e-09                1.223086e-09   
1                   5.835291e-06                1.856717e-06   
2                   1.332064e-07                5.270957e-08   
3                   8.323825e-02                7.759521e-02   
4                   0.000000e+00                0.000000e+00   
...                          ...                         ...   
2

In [54]:
beh = pd.read_csv(DATA_DIR+"behaviorals.csv")
print('Before:'+str(beh.shape))

most_common_disorders = ['Attention-Deficit/Hyperactivity Disorder', 'Anxiety Disorders', 'Specific Learning Disorder',
                         'Autism Spectrum Disorder', 'Disruptive', 'No Diagnosis Given', 'Communication Disorder',
                         'Depressive Disorders']

# most_common_disorders = ['Other Neurodevelopmental Disorders', 'ADHD-Inattentive Type', 'ADHD-Combined Type', 'Anxiety Disorders', 'No Diagnosis Given', 'Depressive Disorders']

category_columns = ['DX_' + str(i).zfill(2) + '_Cat' for i in range(1, 11)] +\
                   ['DX_' + str(i).zfill(2) + '_Sub' for i in range(1, 11)]

# find users that have no diagnosis within these top diseases
# filtering should cahnge anything as this should also happen at a later stage
mask = None
for col in category_columns:
    mask_col = beh[col].isin(most_common_disorders)
    if mask is None:
        mask = mask_col
    else:
        mask = mask | mask_col

initial_size = beh.shape[0]
beh = beh[mask]
beh = beh.reset_index(drop=True)
new_size = beh.shape[0]
print('After:'+str(beh.shape))
print('Removing', initial_size - new_size,
      'patients as their diagnoses were very uncommon.')

Before:(3076, 177)
After:(2813, 177)
Removing 263 patients as their diagnoses were very uncommon.


In [55]:
no_diagnosis_given = 'No Diagnosis Given'

if no_diagnosis_given in most_common_disorders:
    no_diag_index = most_common_disorders.index(no_diagnosis_given)
    most_common_disorders = most_common_disorders[:no_diag_index] + \
        most_common_disorders[no_diag_index + 1:]

diagnoses_to_ids = {disorder: i for i, disorder in enumerate(most_common_disorders)}
diagnoses_to_ids

{'Attention-Deficit/Hyperactivity Disorder': 0,
 'Anxiety Disorders': 1,
 'Specific Learning Disorder': 2,
 'Autism Spectrum Disorder': 3,
 'Disruptive': 4,
 'Communication Disorder': 5,
 'Depressive Disorders': 6}

In [56]:
def get_disorder(data, row, index):
    disorder = data.iloc[row][category_columns[index]]

    if disorder == 'Neurodevelopmental Disorders':
        disorder = data.iloc[row][category_columns[index + 10]]

    return disorder

order_of_disorders = []
for k in range(beh.shape[0]):
    i = 0
    disorder = get_disorder(beh, k, i)
    disorders_patient = []
    while disorder != no_diagnosis_given and not pd.isnull(disorder):
        if disorder in diagnoses_to_ids:
            if diagnoses_to_ids[disorder] not in disorders_patient:
                disorders_patient.append(diagnoses_to_ids[disorder])
        i += 1
        if i == len(category_columns):
            break
        disorder = get_disorder(beh, k, i)

    order_of_disorders.append(disorders_patient)


In [57]:
max_len_order = np.max([len(x) for x in order_of_disorders])

# pad with a new token denoting the pad token
pad_token = len(most_common_disorders)
bod_token = len(most_common_disorders) + 1
eod_token = len(most_common_disorders) + 2

order_of_disorders = [[bod_token] + x + [eod_token] + [pad_token] * (max_len_order - len(x)) for x in order_of_disorders]

order_of_disorders = np.array(order_of_disorders)

classes = np.zeros((len(most_common_disorders),
                    beh.shape[0]), dtype=np.int32)

df_disorders = beh[category_columns]

for i, disorder in enumerate(most_common_disorders):
    mask = df_disorders.select_dtypes(include=[object]). \
        applymap(lambda x: disorder in x if pd.notnull(x) else False)

    disorder_df = df_disorders[mask.any(axis=1)]

    np.add.at(classes[i], disorder_df.index.values, 1)

behaviour_data_columns = beh.columns.values.astype(np.str)

columns_to_drop = behaviour_data_columns[
    np.flatnonzero(np.core.defchararray.find(behaviour_data_columns, 'DX') != -1)]

behaviour_data = beh.drop(columns=columns_to_drop)

for disorder, classification in zip(most_common_disorders, classes):
    behaviour_data[disorder] = classification

behaviour_data['order_diagnoses'] = list(order_of_disorders)


In [58]:
labels=behaviour_data[["IDs"]+list(most_common_disorders)]
labels

IDs  Attention-Deficit/Hyperactivity Disorder  \
0     NDARAA075AMK                                         0   
1     NDARAA112DMH                                         1   
2     NDARAA117NEJ                                         1   
3     NDARAA306NT2                                         1   
4     NDARAA504CRN                                         1   
...            ...                                       ...   
2808  NDARZZ007YMP                                         0   
2809  NDARZZ740MLM                                         1   
2810  NDARZZ810LVF                                         0   
2811  NDARZZ830JM7                                         0   
2812  NDARZZ993CEV                                         0   

      Anxiety Disorders  Specific Learning Disorder  Autism Spectrum Disorder  \
0                     0                           0                         0   
1                     0                           0                         0   
2                     0                           0                         0   
3                     1                           1                         0   
4                     1                           1                         0   
...                 ...                         ...                       ...   
2808                  0                           0                         1   
2809                  0                           0                         0   
2810                  0                           0                         1   
2811                  0                           0                         1   
2812                  1                           0                         0   

      Disruptive  Communication Disorder  Depressive Disorders  
0              0                       0                     0  
1              1                       0                     0  
2              1                       0                     0  
3              0                       1                     0  
4              0                       0                     0  
...          ...                     ...                   ...  
2808           0                       0                     0  
2809           0                       0                     0  
2810           0                       1                     0  
2811           0                       0                     0  
2812           0                       0                     0  

[2813 rows x 8 columns]

In [59]:
df = pd.merge(df, foof, on='IDs', how='inner')
df = pd.merge(df, labels, on='IDs', how='inner')
df

(Electrode 1 - 1/2 Hz,)  (Electrode 1 - 2/2 Hz,)  \
0                7.707834e-12             1.512286e-10   
1                3.798713e-02             1.639433e-01   
2                2.104310e-06             4.299647e-05   
3                1.692639e-01             2.021357e-01   
4                8.332328e-06             1.552379e-04   
...                       ...                      ...   
1831             1.346991e-04             2.668833e-04   
1832             3.397339e-06             1.701445e-05   
1833             8.241315e-06             2.938160e-04   
1834             2.658455e-03             5.749806e-03   
1835             4.856385e-04             3.048976e-03   

      (Electrode 1 - 3/2 Hz,)  (Electrode 1 - 4/2 Hz,)  \
0                2.475735e-09             3.453763e-08   
1                2.897591e-01             2.097609e-01   
2                5.644195e-04             4.760137e-03   
3                2.273063e-01             2.406964e-01   
4                1.804338e-03             1.287033e-02   
...                       ...                      ...   
1831             5.122547e-04             9.524861e-04   
1832             7.576350e-05             2.999317e-04   
1833             4.641777e-03             3.249546e-02   
1834             1.180538e-02             2.300961e-02   
1835             1.546836e-02             5.645783e-02   

      (Electrode 1 - 5/2 Hz,)  (Electrode 1 - 6/2 Hz,)  \
0                4.554996e-07                 0.000007   
1                6.347556e-02                 0.027758   
2                2.579253e-02                 0.089799   
3                2.400039e-01                 0.225430   
4                5.615280e-02                 0.149809   
...                       ...                      ...   
1831             1.715693e-03                 0.002994   
1832             1.055570e-03                 0.003303   
1833             1.008094e-01                 0.138615   
1834             4.257369e-02                 0.074778   
1835             1.419824e-01                 0.245335   

      (Electrode 1 - 7/2 Hz,)  (Electrode 1 - 8/2 Hz,)  \
0                    0.000109                 0.001314   
1                    0.105298                 0.184513   
2                    0.201005                 0.290260   
3                    0.202278                 0.198154   
4                    0.244887                 0.247738   
...                       ...                      ...   
1831                 0.005061                 0.008288   
1832                 0.009185                 0.022711   
1833                 0.084707                 0.024339   
1834                 0.124685                 0.197358   
1835                 0.301591                 0.291822   

      (Electrode 1 - 9/2 Hz,)  (Electrode 1 - 10/2 Hz,)  ...           IDs  \
0                    0.009992                  0.045200  ...  NDARAA075AMK   
1                    0.130638                  0.163258  ...  NDARAA112DMH   
2                    0.276177                  0.196151  ...  NDARAA117NEJ   
3                    0.228356                  0.181836  ...  NDARAA947ZG5   
4                    0.163687                  0.094061  ...  NDARAA948VFH   
...                       ...                       ...  ...           ...   
1831                 0.013148                  0.020205  ...  NDARZM903TNL   
1832                 0.049919                  0.097542  ...  NDARZN148PMN   
1833                 0.009157                  0.021386  ...  NDARZN277NR6   
1834                 0.296551                  0.423009  ...  NDARZN677EYE   
1835                 0.267454                  0.265932  ...  NDARZN899JCM   

      Intercept     Slope  Attention-Deficit/Hyperactivity Disorder  \
0      0.986272  1.825774                                         0   
1      1.486650  1.888544                                         1   
2      1.593155  2.095749                                         1 

### Data Split

In [60]:
x = df[df.columns.difference(['IDs']+most_common_disorders)]
y = df[most_common_disorders]

# summarize dataset shape
print(x.shape, y.shape)

(1836, 8297) (1836, 7)


In [61]:
#scaling features

# data normalization with sklearn
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(x)

# transform training data
x_norm = norm.transform(x)
x_norm = x


/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(


In [65]:


train_features, test_features, train_labels, test_labels = train_test_split(x, y, test_size=0.3, shuffle=True)

### Metrics

In [66]:
from sklearn.metrics import hamming_loss, accuracy_score
import sklearn.metrics as skm
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import numpy as np


def evaluate(y_test, y_pred):
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Hamming Loss:", hamming_loss(y_test, y_pred))
    print("Classification Report:\n", skm.classification_report(y_test,y_pred, zero_division=1))
    print("Confusion matrix:\n", skm.multilabel_confusion_matrix(y_test, y_pred))

## Models

### Multi Output Classifier

In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC as svm
from sklearn.multioutput import MultiOutputClassifier

forest = RandomForestClassifier(random_state=1)
lg = LogisticRegression()
svm = svm()
models = [lg, forest, svm]

for model in models:

    multi_output_model = MultiOutputClassifier(model, n_jobs=-1)
    multi_output_model.fit(train_features, train_labels)
    predicted_labels = multi_output_model.predict(test_features)
    print(str(model)+':')
    evaluate(test_labels, predicted_labels)

/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes:

LogisticRegression():
Accuracy: 0.09437386569872959
Hamming Loss: 0.2605652061187451
Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.75      0.68       333
           1       0.41      0.37      0.39       182
           2       0.24      0.15      0.19       137
           3       0.18      0.12      0.15        72
           4       0.22      0.17      0.19        70
           5       0.17      0.09      0.12        74
           6       0.26      0.09      0.13        58

   micro avg       0.45      0.40      0.42       926
   macro avg       0.30      0.25      0.26       926
weighted avg       0.40      0.40      0.39       926
 samples avg       0.54      0.49      0.37       926

Confusion matrix:
 [[[ 64 154]
  [ 84 249]]

 [[272  97]
  [114  68]]

 [[348  66]
  [116  21]]

 [[437  42]
  [ 63   9]]

 [[438  43]
  [ 58  12]]

 [[443  34]
  [ 67   7]]

 [[479  14]
  [ 53   5]]]


/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes:

RandomForestClassifier(random_state=1):
Accuracy: 0.15970961887477314
Hamming Loss: 0.2172673061965258
Classification Report:
               precision    recall  f1-score   support

           0       0.61      0.95      0.74       333
           1       0.36      0.08      0.13       182
           2       0.25      0.01      0.01       137
           3       0.00      0.00      0.00        72
           4       0.00      0.00      0.00        70
           5       0.00      0.00      0.00        74
           6       1.00      0.02      0.03        58

   micro avg       0.58      0.36      0.44       926
   macro avg       0.32      0.15      0.13       926
weighted avg       0.39      0.36      0.30       926
 samples avg       0.61      0.48      0.41       926

Confusion matrix:
 [[[ 13 205]
  [ 15 318]]

 [[342  27]
  [167  15]]

 [[411   3]
  [136   1]]

 [[473   6]
  [ 72   0]]

 [[476   5]
  [ 70   0]]

 [[476   1]
  [ 74   0]]

 [[493   0]
  [ 57   1]]]


/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes:

SVC():
Accuracy: 0.1705989110707804
Hamming Loss: 0.210267046927664
Classification Report:
               precision    recall  f1-score   support

           0       0.60      1.00      0.75       333
           1       1.00      0.00      0.00       182
           2       1.00      0.00      0.00       137
           3       1.00      0.00      0.00        72
           4       1.00      0.00      0.00        70
           5       1.00      0.00      0.00        74
           6       1.00      0.00      0.00        58

   micro avg       0.60      0.36      0.45       926
   macro avg       0.94      0.14      0.11       926
weighted avg       0.86      0.36      0.27       926
 samples avg       0.60      0.48      0.42       926

Confusion matrix:
 [[[  0 218]
  [  0 333]]

 [[369   0]
  [182   0]]

 [[414   0]
  [137   0]]

 [[479   0]
  [ 72   0]]

 [[481   0]
  [ 70   0]]

 [[477   0]
  [ 74   0]]

 [[493   0]
  [ 58   0]]]


### MLP

In [38]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def get_mlp(n_inputs, n_outputs):
    model = Sequential()
    model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
    model.add(Dense(n_outputs, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    return model

n_inputs, n_outputs = x.shape[1], y.shape[1]
mlp = get_mlp(n_inputs, n_outputs)
mlp.fit(train_features, train_labels, verbose=1, epochs=100)

Epoch 1/100
41/41 [==============================] - 0s 2ms/step - loss: 0.5340
Epoch 2/100
41/41 [==============================] - 0s 2ms/step - loss: 0.5056
Epoch 3/100
41/41 [==============================] - 0s 2ms/step - loss: 0.5050
Epoch 4/100
41/41 [==============================] - 0s 2ms/step - loss: 0.4966
Epoch 5/100
41/41 [==============================] - 0s 2ms/step - loss: 0.4920
Epoch 6/100
41/41 [==============================] - 0s 2ms/step - loss: 0.4835
Epoch 7/100
41/41 [==============================] - 0s 2ms/step - loss: 0.4846
Epoch 8/100
41/41 [==============================] - 0s 2ms/step - loss: 0.4822
Epoch 9/100
41/41 [==============================] - 0s 2ms/step - loss: 0.4718
Epoch 10/100
41/41 [==============================] - 0s 2ms/step - loss: 0.4684
Epoch 11/100
41/41 [==============================] - 0s 2ms/step - loss: 0.4658
Epoch 12/100
41/41 [==============================] - 0s 2ms/step - loss: 0.4682
Epoch 13/100
41/41 [=================

In [39]:
predicted_labels_mlp = mlp.predict(test_features)
evaluate(test_labels, predicted_labels_mlp.round())

Accuracy: 0.0852994555353902
Hamming Loss: 0.2719730360383718
Classification Report:
               precision    recall  f1-score   support

           0       0.66      0.86      0.74       350
           1       0.40      0.50      0.44       196
           2       0.20      0.28      0.24       118
           3       0.15      0.04      0.06        82
           4       0.15      0.03      0.06        89
           5       0.35      0.07      0.12        99
           6       0.17      0.11      0.13        55

   micro avg       0.47      0.46      0.46       989
   macro avg       0.30      0.27      0.26       989
weighted avg       0.41      0.46      0.41       989
 samples avg       0.53      0.55      0.42       989

Confusion matrix:
 [[[ 43 158]
  [ 49 301]]

 [[208 147]
  [ 98  98]]

 [[304 129]
  [ 85  33]]

 [[452  17]
  [ 79   3]]

 [[445  17]
  [ 86   3]]

 [[439  13]
  [ 92   7]]

 [[466  30]
  [ 49   6]]]


### Binary Relevance
ignores the possible correlations between class labels

In [68]:
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import GaussianNB

classifier = BinaryRelevance(GaussianNB())
classifier.fit(test_features, test_labels)

BinaryRelevance(classifier=GaussianNB(), require_dense=[True, True])

In [69]:
predicted_labels_br = classifier.predict(test_features)
evaluate(test_labels, predicted_labels_br)

/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes:

Accuracy: 0.06715063520871144
Hamming Loss: 0.42105263157894735
Classification Report:
               precision    recall  f1-score   support

           0       0.68      0.82      0.74       333
           1       0.37      0.81      0.51       182
           2       0.32      0.82      0.46       137
           3       0.21      0.81      0.34        72
           4       0.17      0.69      0.28        70
           5       0.22      0.47      0.30        74
           6       0.18      0.90      0.30        58

   micro avg       0.34      0.78      0.47       926
   macro avg       0.31      0.76      0.42       926
weighted avg       0.42      0.78      0.52       926
 samples avg       0.39      0.81      0.44       926

Confusion matrix:
 [[[ 90 128]
  [ 61 272]]

 [[118 251]
  [ 35 147]]

 [[171 243]
  [ 25 112]]

 [[265 214]
  [ 14  58]]

 [[251 230]
  [ 22  48]]

 [[353 124]
  [ 39  35]]

 [[261 232]
  [  6  52]]]


/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(


### Classfier Chains

In [70]:
from skmultilearn.problem_transform import ClassifierChain
from sklearn.linear_model import LogisticRegression

classifier = ClassifierChain(LogisticRegression())
classifier.fit(train_features, train_labels)
# we should optimise this a little

/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/lin

ClassifierChain(classifier=LogisticRegression(), require_dense=[True, True])

In [71]:
predicted_labels_cc = classifier.predict(test_features)
evaluate(test_labels, predicted_labels_cc)

Accuracy: 0.10163339382940109
Hamming Loss: 0.26549131449312935
Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.75      0.68       333
           1       0.39      0.36      0.37       182
           2       0.23      0.15      0.18       137
           3       0.16      0.12      0.14        72
           4       0.22      0.17      0.19        70
           5       0.13      0.07      0.09        74
           6       0.30      0.12      0.17        58

   micro avg       0.44      0.40      0.42       926
   macro avg       0.29      0.25      0.26       926
weighted avg       0.39      0.40      0.39       926
 samples avg       0.53      0.49      0.37       926

Confusion matrix:
 [[[ 64 154]
  [ 84 249]]

 [[266 103]
  [117  65]]

 [[343  71]
  [116  21]]

 [[433  46]
  [ 63   9]]

 [[438  43]
  [ 58  12]]

 [[444  33]
  [ 69   5]]

 [[477  16]
  [ 51   7]]]


### Label Powerset
takes correlations into account!

In [72]:
from skmultilearn.problem_transform import LabelPowerset

classifier = LabelPowerset(LogisticRegression())
classifier.fit(train_features, train_labels)

/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LabelPowerset(classifier=LogisticRegression(), require_dense=[True, True])

In [73]:
predicted_labels_lp = classifier.predict(test_features)
evaluate(test_labels, predicted_labels_lp)

/home/ubuntu/anaconda3/envs/ai4halth/lib/python3.8/site-packages/sklearn/utils/validation.py:1675: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  warnings.warn(


Accuracy: 0.0925589836660617
Hamming Loss: 0.2802696396162821
Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.67      0.62       333
           1       0.40      0.32      0.36       182
           2       0.24      0.18      0.21       137
           3       0.26      0.21      0.23        72
           4       0.16      0.16      0.16        70
           5       0.15      0.09      0.12        74
           6       0.19      0.14      0.16        58

   micro avg       0.41      0.37      0.39       926
   macro avg       0.28      0.25      0.26       926
weighted avg       0.38      0.37      0.37       926
 samples avg       0.51      0.48      0.35       926

Confusion matrix:
 [[[ 62 156]
  [111 222]]

 [[279  90]
  [123  59]]

 [[333  81]
  [112  25]]

 [[436  43]
  [ 57  15]]

 [[424  57]
  [ 59  11]]

 [[437  40]
  [ 67   7]]

 [[458  35]
  [ 50   8]]]


### Multi Label KNN

In [74]:
from skmultilearn.adapt import MLkNN
from scipy.sparse import csr_matrix, lil_matrix

mlknn = MLkNN(k=10)

x_train = lil_matrix(train_features).toarray()
y_train = lil_matrix(train_labels).toarray()
x_test = lil_matrix(test_features).toarray()
# train
mlknn.fit(x_train, y_train)
# predict
# predictions_new = classifier_new.predict(x_test)
# # accuracy
# print("Accuracy = ",accuracy_score(y_test,predictions_new))
# print("\n")


TypeError: __init__() takes 1 positional argument but 2 were given

In [ ]:
predicted_labels_mlknn = mlknn.predict(x_test)
evaluate(test_labels, predicted_labels_mlknn)

AttributeError: 'MLkNN' object has no attribute 'knn_'